# Generated by Django 4.2.9 on 2024-02-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.ImageField(default=1, upload_to='details'),
            preserve_default=False,
        ),
    ]
